//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Support: http://www.cnblogs.com/huxj
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace Dos.Model
{

	/// <summary>
	/// 实体类tb_Training 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Serializable]
	public partial class tb_Training : Entity 
	{
		public tb_Training():base("tb_Training") {}

		#region Model
		private int _c00;
		private string _TRName;
		private string _TRSex;
		private string _TRIdCardNumber;
		private string _TRPhone;
		private string _TRCompany;
		private DateTime? _TrainingDate;
		private DateTime? _CreateDate;
		/// <summary>
		/// 
		/// </summary>
		public int c00
		{
			get{ return _c00; }
			set
			{
				this.OnPropertyValueChange(_.c00,_c00,value);
				this._c00=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string TRName
		{
			get{ return _TRName; }
			set
			{
				this.OnPropertyValueChange(_.TRName,_TRName,value);
				this._TRName=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string TRSex
		{
			get{ return _TRSex; }
			set
			{
				this.OnPropertyValueChange(_.TRSex,_TRSex,value);
				this._TRSex=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string TRIdCardNumber
		{
			get{ return _TRIdCardNumber; }
			set
			{
				this.OnPropertyValueChange(_.TRIdCardNumber,_TRIdCardNumber,value);
				this._TRIdCardNumber=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string TRPhone
		{
			get{ return _TRPhone; }
			set
			{
				this.OnPropertyValueChange(_.TRPhone,_TRPhone,value);
				this._TRPhone=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string TRCompany
		{
			get{ return _TRCompany; }
			set
			{
				this.OnPropertyValueChange(_.TRCompany,_TRCompany,value);
				this._TRCompany=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? TrainingDate
		{
			get{ return _TrainingDate; }
			set
			{
				this.OnPropertyValueChange(_.TrainingDate,_TrainingDate,value);
				this._TrainingDate=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? CreateDate
		{
			get{ return _CreateDate; }
			set
			{
				this.OnPropertyValueChange(_.CreateDate,_CreateDate,value);
				this._CreateDate=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的标识列
		/// </summary>
		public override Field GetIdentityField()
		{
			return _.c00;
		}
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.c00};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.c00,
				_.TRName,
				_.TRSex,
				_.TRIdCardNumber,
				_.TRPhone,
				_.TRCompany,
				_.TrainingDate,
				_.CreateDate};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._c00,
				this._TRName,
				this._TRSex,
				this._TRIdCardNumber,
				this._TRPhone,
				this._TRCompany,
				this._TrainingDate,
				this._CreateDate};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","tb_Training");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field c00 = new Field("c00","tb_Training","c00");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field TRName = new Field("TRName","tb_Training","TRName");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field TRSex = new Field("TRSex","tb_Training","TRSex");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field TRIdCardNumber = new Field("TRIdCardNumber","tb_Training","TRIdCardNumber");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field TRPhone = new Field("TRPhone","tb_Training","TRPhone");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field TRCompany = new Field("TRCompany","tb_Training","TRCompany");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field TrainingDate = new Field("TrainingDate","tb_Training","TrainingDate");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CreateDate = new Field("CreateDate","tb_Training","CreateDate");
		}
		#endregion


	}
}

