//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Support: http://www.cnblogs.com/huxj
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace Dos.Model
{

	/// <summary>
	/// 实体类v_Examiner 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Serializable]
	public partial class v_Examiner : Entity 
	{
		public v_Examiner():base("v_Examiner") {}

		#region Model
		private string _FlowStateName;
		private string _ExamName;
		private DateTime? _StartDate;
		private DateTime? _EndDate;
		private decimal? _PassScore;
		private int _ExaminerID;
		private string _GUID;
		private string _ExaminerName;
		private int? _ExamID;
		private int? _ExamUnitID;
		private string _Sex;
		private string _PhotoPath;
		private string _SignPath;
		private string _ContractPath;
		private string _IdCardNumber;
		private string _Phone;
		private string _ZYJSZC;
		private string _ZCZYMC;
		private string _GraduateSchool;
		private DateTime? _WorkDate;
		private string _Degree;
		private string _Major;
		private DateTime? _GraduationDate;
		private string _Email;
		private string _WorkUnit;
		private string _WorkPerformance;
		private int? _FlowStateID;
		private string _Examinee;
		private decimal? _Score;
		private DateTime? _CreateDate;
		private string _ExamHeadName;
		private int? _Age;
		private string _Batch;
		private string _RefuseReason;
		private int? _WorkAge;
		private int? _CompanyID;
		private string _CompanyName;
		private string _CompanyAddress;
		private int? _OperationUserId;
		private string _OperationUserName;
		/// <summary>
		/// 
		/// </summary>
		public string FlowStateName
		{
			get{ return _FlowStateName; }
			set
			{
				this.OnPropertyValueChange(_.FlowStateName,_FlowStateName,value);
				this._FlowStateName=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string ExamName
		{
			get{ return _ExamName; }
			set
			{
				this.OnPropertyValueChange(_.ExamName,_ExamName,value);
				this._ExamName=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? StartDate
		{
			get{ return _StartDate; }
			set
			{
				this.OnPropertyValueChange(_.StartDate,_StartDate,value);
				this._StartDate=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? EndDate
		{
			get{ return _EndDate; }
			set
			{
				this.OnPropertyValueChange(_.EndDate,_EndDate,value);
				this._EndDate=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public decimal? PassScore
		{
			get{ return _PassScore; }
			set
			{
				this.OnPropertyValueChange(_.PassScore,_PassScore,value);
				this._PassScore=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int ExaminerID
		{
			get{ return _ExaminerID; }
			set
			{
				this.OnPropertyValueChange(_.ExaminerID,_ExaminerID,value);
				this._ExaminerID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string GUID
		{
			get{ return _GUID; }
			set
			{
				this.OnPropertyValueChange(_.GUID,_GUID,value);
				this._GUID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string ExaminerName
		{
			get{ return _ExaminerName; }
			set
			{
				this.OnPropertyValueChange(_.ExaminerName,_ExaminerName,value);
				this._ExaminerName=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? ExamID
		{
			get{ return _ExamID; }
			set
			{
				this.OnPropertyValueChange(_.ExamID,_ExamID,value);
				this._ExamID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? ExamUnitID
		{
			get{ return _ExamUnitID; }
			set
			{
				this.OnPropertyValueChange(_.ExamUnitID,_ExamUnitID,value);
				this._ExamUnitID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Sex
		{
			get{ return _Sex; }
			set
			{
				this.OnPropertyValueChange(_.Sex,_Sex,value);
				this._Sex=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string PhotoPath
		{
			get{ return _PhotoPath; }
			set
			{
				this.OnPropertyValueChange(_.PhotoPath,_PhotoPath,value);
				this._PhotoPath=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string SignPath
		{
			get{ return _SignPath; }
			set
			{
				this.OnPropertyValueChange(_.SignPath,_SignPath,value);
				this._SignPath=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string ContractPath
		{
			get{ return _ContractPath; }
			set
			{
				this.OnPropertyValueChange(_.ContractPath,_ContractPath,value);
				this._ContractPath=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string IdCardNumber
		{
			get{ return _IdCardNumber; }
			set
			{
				this.OnPropertyValueChange(_.IdCardNumber,_IdCardNumber,value);
				this._IdCardNumber=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Phone
		{
			get{ return _Phone; }
			set
			{
				this.OnPropertyValueChange(_.Phone,_Phone,value);
				this._Phone=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string ZYJSZC
		{
			get{ return _ZYJSZC; }
			set
			{
				this.OnPropertyValueChange(_.ZYJSZC,_ZYJSZC,value);
				this._ZYJSZC=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string ZCZYMC
		{
			get{ return _ZCZYMC; }
			set
			{
				this.OnPropertyValueChange(_.ZCZYMC,_ZCZYMC,value);
				this._ZCZYMC=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string GraduateSchool
		{
			get{ return _GraduateSchool; }
			set
			{
				this.OnPropertyValueChange(_.GraduateSchool,_GraduateSchool,value);
				this._GraduateSchool=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? WorkDate
		{
			get{ return _WorkDate; }
			set
			{
				this.OnPropertyValueChange(_.WorkDate,_WorkDate,value);
				this._WorkDate=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Degree
		{
			get{ return _Degree; }
			set
			{
				this.OnPropertyValueChange(_.Degree,_Degree,value);
				this._Degree=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Major
		{
			get{ return _Major; }
			set
			{
				this.OnPropertyValueChange(_.Major,_Major,value);
				this._Major=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? GraduationDate
		{
			get{ return _GraduationDate; }
			set
			{
				this.OnPropertyValueChange(_.GraduationDate,_GraduationDate,value);
				this._GraduationDate=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Email
		{
			get{ return _Email; }
			set
			{
				this.OnPropertyValueChange(_.Email,_Email,value);
				this._Email=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string WorkUnit
		{
			get{ return _WorkUnit; }
			set
			{
				this.OnPropertyValueChange(_.WorkUnit,_WorkUnit,value);
				this._WorkUnit=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string WorkPerformance
		{
			get{ return _WorkPerformance; }
			set
			{
				this.OnPropertyValueChange(_.WorkPerformance,_WorkPerformance,value);
				this._WorkPerformance=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? FlowStateID
		{
			get{ return _FlowStateID; }
			set
			{
				this.OnPropertyValueChange(_.FlowStateID,_FlowStateID,value);
				this._FlowStateID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Examinee
		{
			get{ return _Examinee; }
			set
			{
				this.OnPropertyValueChange(_.Examinee,_Examinee,value);
				this._Examinee=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public decimal? Score
		{
			get{ return _Score; }
			set
			{
				this.OnPropertyValueChange(_.Score,_Score,value);
				this._Score=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? CreateDate
		{
			get{ return _CreateDate; }
			set
			{
				this.OnPropertyValueChange(_.CreateDate,_CreateDate,value);
				this._CreateDate=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string ExamHeadName
		{
			get{ return _ExamHeadName; }
			set
			{
				this.OnPropertyValueChange(_.ExamHeadName,_ExamHeadName,value);
				this._ExamHeadName=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? Age
		{
			get{ return _Age; }
			set
			{
				this.OnPropertyValueChange(_.Age,_Age,value);
				this._Age=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Batch
		{
			get{ return _Batch; }
			set
			{
				this.OnPropertyValueChange(_.Batch,_Batch,value);
				this._Batch=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string RefuseReason
		{
			get{ return _RefuseReason; }
			set
			{
				this.OnPropertyValueChange(_.RefuseReason,_RefuseReason,value);
				this._RefuseReason=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? WorkAge
		{
			get{ return _WorkAge; }
			set
			{
				this.OnPropertyValueChange(_.WorkAge,_WorkAge,value);
				this._WorkAge=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? CompanyID
		{
			get{ return _CompanyID; }
			set
			{
				this.OnPropertyValueChange(_.CompanyID,_CompanyID,value);
				this._CompanyID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string CompanyName
		{
			get{ return _CompanyName; }
			set
			{
				this.OnPropertyValueChange(_.CompanyName,_CompanyName,value);
				this._CompanyName=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string CompanyAddress
		{
			get{ return _CompanyAddress; }
			set
			{
				this.OnPropertyValueChange(_.CompanyAddress,_CompanyAddress,value);
				this._CompanyAddress=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? OperationUserId
		{
			get{ return _OperationUserId; }
			set
			{
				this.OnPropertyValueChange(_.OperationUserId,_OperationUserId,value);
				this._OperationUserId=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string OperationUserName
		{
			get{ return _OperationUserName; }
			set
			{
				this.OnPropertyValueChange(_.OperationUserName,_OperationUserName,value);
				this._OperationUserName=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 是否只读
		/// </summary>
		public override bool IsReadOnly()
		{
			return true;
		}
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.ExaminerID};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.FlowStateName,
				_.ExamName,
				_.StartDate,
				_.EndDate,
				_.PassScore,
				_.ExaminerID,
				_.GUID,
				_.ExaminerName,
				_.ExamID,
				_.ExamUnitID,
				_.Sex,
				_.PhotoPath,
				_.SignPath,
				_.ContractPath,
				_.IdCardNumber,
				_.Phone,
				_.ZYJSZC,
				_.ZCZYMC,
				_.GraduateSchool,
				_.WorkDate,
				_.Degree,
				_.Major,
				_.GraduationDate,
				_.Email,
				_.WorkUnit,
				_.WorkPerformance,
				_.FlowStateID,
				_.Examinee,
				_.Score,
				_.CreateDate,
				_.ExamHeadName,
				_.Age,
				_.Batch,
				_.RefuseReason,
				_.WorkAge,
				_.CompanyID,
				_.CompanyName,
				_.CompanyAddress,
				_.OperationUserId,
				_.OperationUserName};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._FlowStateName,
				this._ExamName,
				this._StartDate,
				this._EndDate,
				this._PassScore,
				this._ExaminerID,
				this._GUID,
				this._ExaminerName,
				this._ExamID,
				this._ExamUnitID,
				this._Sex,
				this._PhotoPath,
				this._SignPath,
				this._ContractPath,
				this._IdCardNumber,
				this._Phone,
				this._ZYJSZC,
				this._ZCZYMC,
				this._GraduateSchool,
				this._WorkDate,
				this._Degree,
				this._Major,
				this._GraduationDate,
				this._Email,
				this._WorkUnit,
				this._WorkPerformance,
				this._FlowStateID,
				this._Examinee,
				this._Score,
				this._CreateDate,
				this._ExamHeadName,
				this._Age,
				this._Batch,
				this._RefuseReason,
				this._WorkAge,
				this._CompanyID,
				this._CompanyName,
				this._CompanyAddress,
				this._OperationUserId,
				this._OperationUserName};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","v_Examiner");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field FlowStateName = new Field("FlowStateName","v_Examiner","FlowStateName");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ExamName = new Field("ExamName","v_Examiner","ExamName");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field StartDate = new Field("StartDate","v_Examiner","StartDate");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field EndDate = new Field("EndDate","v_Examiner","EndDate");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field PassScore = new Field("PassScore","v_Examiner","PassScore");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ExaminerID = new Field("ExaminerID","v_Examiner","ExaminerID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field GUID = new Field("GUID","v_Examiner","GUID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ExaminerName = new Field("ExaminerName","v_Examiner","ExaminerName");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ExamID = new Field("ExamID","v_Examiner","ExamID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ExamUnitID = new Field("ExamUnitID","v_Examiner","ExamUnitID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Sex = new Field("Sex","v_Examiner","Sex");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field PhotoPath = new Field("PhotoPath","v_Examiner","PhotoPath");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SignPath = new Field("SignPath","v_Examiner","SignPath");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ContractPath = new Field("ContractPath","v_Examiner","ContractPath");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field IdCardNumber = new Field("IdCardNumber","v_Examiner","IdCardNumber");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Phone = new Field("Phone","v_Examiner","Phone");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ZYJSZC = new Field("ZYJSZC","v_Examiner","ZYJSZC");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ZCZYMC = new Field("ZCZYMC","v_Examiner","ZCZYMC");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field GraduateSchool = new Field("GraduateSchool","v_Examiner","GraduateSchool");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field WorkDate = new Field("WorkDate","v_Examiner","WorkDate");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Degree = new Field("Degree","v_Examiner","Degree");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Major = new Field("Major","v_Examiner","Major");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field GraduationDate = new Field("GraduationDate","v_Examiner","GraduationDate");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Email = new Field("Email","v_Examiner","Email");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field WorkUnit = new Field("WorkUnit","v_Examiner","WorkUnit");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field WorkPerformance = new Field("WorkPerformance","v_Examiner","WorkPerformance");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field FlowStateID = new Field("FlowStateID","v_Examiner","FlowStateID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Examinee = new Field("Examinee","v_Examiner","Examinee");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Score = new Field("Score","v_Examiner","Score");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CreateDate = new Field("CreateDate","v_Examiner","CreateDate");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ExamHeadName = new Field("ExamHeadName","v_Examiner","ExamHeadName");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Age = new Field("Age","v_Examiner","Age");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Batch = new Field("Batch","v_Examiner","Batch");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field RefuseReason = new Field("RefuseReason","v_Examiner","RefuseReason");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field WorkAge = new Field("WorkAge","v_Examiner","WorkAge");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CompanyID = new Field("CompanyID","v_Examiner","CompanyID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CompanyName = new Field("CompanyName","v_Examiner","CompanyName");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CompanyAddress = new Field("CompanyAddress","v_Examiner","CompanyAddress");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field OperationUserId = new Field("OperationUserId","v_Examiner","OperationUserId");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field OperationUserName = new Field("OperationUserName","v_Examiner","OperationUserName");
		}
		#endregion


	}
}

